# Generated by Django 5.1.6 on 2025-02-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_order_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ammount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
