# Generated by Django 5.1.6 on 2025-02-25 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_order_ammount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ammount',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.order')),
            ],
        ),
    ]
